os: Windows Server 2012 R2

clone_folder: c:\gopath\src\mumble.info\cygwin-bootstrap

environment:
  GOPATH: c:\gopath

install:
  - go get -v -t ./...

build_script:
  - go build mumble.info/cygwin-bootstrap
  - go test -v ./...
